api/urls.py
from rest_framework import routers
from django.urls import path, include
from . import views

app_name = "shop_api"

router = routers.DefaultRouter()

# http://127.0.0.1:8000/api/category/",
# http://127.0.0.1:8000/api/category/1/",

router.register("category", views.CategoryViewSet)
router.register("product", views.ProductViewSet)
router.register("post", views.PostViewSet)
router.register("user", views.UserViewSet)
router.register("order", views.OrderViewSet)


urlpatterns = [
    path("", include(router.urls)),
    path("login/", views.Login.as_view(), name="login"),
    path("signup/", views.Signup.as_view(), name="signup"),
    path(
        "orderitem/<pk>/", views.OrderItemDetailView.as_view(), name="orderitem_detail"
    ),
    path(
        "orderlist/<username>/", views.OrderListDetailView.as_view(), name="order_list"
    ),
    path("iot/", views.iot_esp8266View.as_view()),
    path("getDustData/", views.getDustData.as_view()),
    path("getCoronaData/", views.getCoronaData.as_view()),
    path("getWeatherData/<city>/", views.getWeatherData.as_view()),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

coupons/urls.py
from django.urls import path
from . import views

app_name = 'coupons'

urlpatterns = [
    path('apply/', views.coupon_apply, name='apply'),
]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('admin/order/<int:order_id>/', views.admin_order_detail, name='admin_order_detail'),
    path('admin/order/<int:order_id>/pdf/', views.admin_order_pdf, name='admin_order_pdf'),
]

shop/urls.py
from django.urls import path
from . import views

app_name = "shop"

urlpatterns = [
    path("", views.product_list, name="product_list"),
    path("<slug:category_slug>/", views.product_list, name="product_list_by_category"),
    path("<int:id>/<slug:slug>/", views.product_detail, name="product_detail"),
    path("customer/profile/", views.profile, name="customer_profile"),
    path(
        "customer/profile/create/", views.profile_create, name="customer_profile_create"
    ),
    path("customer/ordered_list/", views.ordered_list, name="customer_ordered_list"),
    path("product/like/<int:product_id>", views.product_like, name="product_like"),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 11)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    override = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
#from shop.recommender import Recommender
from coupons.forms import CouponApplyForm
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):      #293
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], override_quantity=cd['override'])
    return redirect('cart:cart_detail')



@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')



def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'override': True})
    
    coupon_apply_form = CouponApplyForm()

    #r = Recommender()
    #cart_products = [item['product'] for item in cart]
    #recommended_products = r.suggest_products_for(cart_products, max_results=4)

    return render(request, 'cart/detail.html', {'cart': cart, 'coupon_apply_form': coupon_apply_form })
                    # 'recommended_products': recommended_products

cart/templates/cart/detail.html
{% extends "base.html" %}
{% load static %}
{% load humanize %}

{% block title %}
  장바구니
{% endblock %}

{% block content %}
<div class="container my-3">
  <h5 class="border-bottom py-3">장바구니</h5>

  <table class="cart" style="width:100%">
    <thead>
      <tr>
        <th colspan="2" style="text-align: center;">상품</th>
        <th colspan="2" style="text-align: center;">수량</th>
        <th style="text-align: center;">단가</th>
        <!-- <th style="text-align: center;">금액</th> -->
      </tr>
    </thead>

    <tbody>
      {% for item in cart %}
        {% with product=item.product %}
          <tr>
            <td>
              <a href="{{ product.get_absolute_url }}">
                  <img src="{% if product.image %}
                    {{ product.image.url }}
                  {% else %}
                    {% static 'img/no_image.png' %}
                  {% endif %}">
              </a>
            </td>

            <td><a href="{{ product.get_absolute_url }}">
              {{ product.name|truncatechars:40 }}</a>
            </td>

            <td>
              <form action="{% url 'cart:cart_add' product.id %}" method="post">
                {{ item.update_quantity_form.quantity }}
                {{ item.update_quantity_form.override }}
                <!-- <input type="submit" class="btn btn-primary btn-sm" value="수정"> -->
                <input type="submit" class="btn btn-primary btn-sm" value="수정">
                {% csrf_token %}
              </form>
            </td>

            <td>
              <form action="{% url 'cart:cart_remove' product.id %}" method="post">
                <!-- <input type="submit" class="btn btn-primary btn-sm" value="삭제"> -->
                <input type="submit" class="btn btn-primary btn-sm" value="삭제">
                {% csrf_token %}
              </form>
            </td>

            <td class="num">{{ item.price|intcomma }}원</td>
            <!-- <td class="num">{{ item.total_price|intcomma }}원</td> -->
          </tr>
        {% endwith %}
      {% endfor %}

      {% if cart.coupon %}
        <tr class="subtotal">
          <td></td>
          <td colspan="2">합계</td>
          <td colspan="2" class="num">{{ cart.get_total_price|intcomma }}원</td>
        </tr>

        <tr>
          <td></td>
          <td colspan="2" style="text-align: left;">쿠폰: {{ cart.coupon.code }} ({{ cart.coupon.discount }}% DC)</td>
          <td colspan="2" class="num neg"> -{{ cart.get_discount|floatformat:0|intcomma }}원</td>
        </tr>
      {% endif %}

      <tr class="total">
        <td></td>
        <td colspan="2" style="text-align: right;">총 결재 금액</td>
        <td colspan="2" class="num">
          {{ cart.get_total_price_after_discount|floatformat:0|intcomma }}원
        </td>
      </tr>
    </tbody>
  </table>

  
  <form action="{% url 'coupons:apply' %}" method="post">
    {% csrf_token %}
    {{ coupon_apply_form }}
    <button type="submit" class="btn btn-primary btn-sm">할인 적용</button>
  </form>
  
  <p class="text-right my-3">
    <a href="{% url 'shop:product_list' %}" class="button light">계속 쇼핑</a>

    {% with total_items=cart|length %}
      {% if total_items > 0 %}
        <!-- 빠르게 2번 클릭할 경우 다른 order_id로 2번 주문이 발생할 수 있다. 처리할 것 -->
        <a href="{% url 'orders:order_create' %}" class="button">주문하기</a>
      {% endif %}
    {% endwith %}
  </p>

</div>
{% endblock %}