api/urls.py
from rest_framework import routers
from django.urls import path, include
from . import views

app_name = "shop_api"

router = routers.DefaultRouter()

# http://127.0.0.1:8000/api/category/",
# http://127.0.0.1:8000/api/category/1/",

router.register("category", views.CategoryViewSet)
router.register("product", views.ProductViewSet)
router.register("post", views.PostViewSet)
router.register("user", views.UserViewSet)
router.register("order", views.OrderViewSet)


urlpatterns = [
    path("", include(router.urls)),
    path("login/", views.Login.as_view(), name="login"),
    path("signup/", views.Signup.as_view(), name="signup"),
    path(
        "orderitem/<pk>/", views.OrderItemDetailView.as_view(), name="orderitem_detail"
    ),
    path(
        "orderlist/<username>/", views.OrderListDetailView.as_view(), name="order_list"
    ),
    path("iot/", views.iot_esp8266View.as_view()),
    path("getDustData/", views.getDustData.as_view()),
    path("getCoronaData/", views.getCoronaData.as_view()),
    path("getWeatherData/<city>/", views.getWeatherData.as_view()),
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:post_id>/', views.detail, name='detail'),
    path('create/<int:product_id>', views.post_create, name='post_create'),
    path('modify/<int:post_id>/', views.post_modify, name='post_modify'),
    path('delete/<int:post_id>/', views.post_delete, name='post_delete'),

    path('vote/<int:post_id>', views.post_vote, name='post_vote'),

    path('<int:post_id>/comment/create/', views.comment_create, name='comment_create'),
    path('comment/modify/<int:comment_id>/', views.comment_modify, name='comment_modify'),
    path('comment/delete/<int:comment_id>/', views.comment_delete, name='comment_delete'),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

shop/urls.py
from django.urls import path
from . import views

app_name = "shop"

urlpatterns = [
    path("", views.product_list, name="product_list"),
    path("<slug:category_slug>/", views.product_list, name="product_list_by_category"),
    path("<int:id>/<slug:slug>/", views.product_detail, name="product_detail"),
    path("customer/profile/", views.profile, name="customer_profile"),
    path(
        "customer/profile/create/", views.profile_create, name="customer_profile_create"
    ),
    path("customer/ordered_list/", views.ordered_list, name="customer_ordered_list"),
    path("product/like/<int:product_id>", views.product_like, name="product_like"),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from shop.models import Product
from django.utils import timezone


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', '비공개'), ('published', '공개'),
    )
    title = models.CharField(max_length=250)
    body = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_post')

    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    #publish = models.DateTimeField(default=timezone.now)       #admin, for date_hierarchy 
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='published')

    voter = models.ManyToManyField(User, related_name='voter_post')
    #post.voter.all() = <QuerySet [<User: admin>, <User: ojonghwa>]>  
    #post.author.voter_post.all() = [<QuerySet [<Post: 공부해 봅시다.>, <Post: 도킨스가 칭찬할 만하다>,
    #request.user.voter_post.all()  #조회
    
    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return self.title


class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    class Meta:
        ordering = ('created',)
        

shop/models.py
from django.core import validators
from django.db import models
from django.urls import reverse
from django.conf import settings
from django.core.validators import MinValueValidator, MaxValueValidator
from datetime import date
from django.contrib.auth.models import User
 

class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ("name",)
        verbose_name = "category"
        verbose_name_plural = "categories"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("shop:product_list_by_category", args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(
        Category, related_name="products", on_delete=models.CASCADE
    )
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(
        upload_to="products/%Y/%m/%d", blank=True
    )  # utils.py  uuid_name_upload_to(instance, filename)

    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=0)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    publication_date = models.DateField(blank=True, default=date(2021, 8, 7))
    # from datetime import date
    # book.publication_date = date(2021,8,7)
    isbn = models.CharField(max_length=20, blank=True, default="ISBN")
    publisher = models.CharField(max_length=50, blank=True, default="PUBL")
    contributors = models.CharField(max_length=100, blank=True, default="CONT")

    likers = models.ManyToManyField(
        User, through="Like", related_name="like_products"
    )  # symmetrical=False

    class Meta:
        ordering = ("name",)
        index_together = (("id", "slug"),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("shop:product_detail", args=[self.id, self.slug])
        # path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),


class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    grade = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])
    # post1.likers.add(request.user ) 사용불가
    # user1.likeposts.add(post1 )  사용불가
    # like_grade = Like.objects.create(user=user1, product=product1, grade=5)
    # product1.likers.all()
    # user1.like_products.all()


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    # 현 계정 사용자를 가져옴
    fullname = models.CharField(max_length=50, db_index=True, blank=True)
    address = models.CharField(max_length=250, blank=True)
    postal_code = models.CharField(max_length=20, blank=True)
    mobile = models.CharField(max_length=30, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ("fullname",)

    def __str__(self):
        return self.fullname

    def get_absolute_url(self):
        return reverse("shop:user_profile", args=[self.user])

shop/forms.py
from django import forms
from .models import Like, Profile
from .widgets import starWidget


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['fullname', 'address', 'postal_code', 'mobile']
        labels = {
            'fullname'   : '이름',
            'address'    : '주소',
            'postal_code': '우편번호',
            'mobile'     : '전화번호',
        }


class LikeForm(forms.ModelForm):
    class Meta:
        model = Like
        fields = ['user', 'product', 'grade']
        labels = {
            'grade'   : '평점',
        }
        widgets = {
            'grade':starWidget
        }

shop/views.py
from django.http.response import JsonResponse
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.contrib.auth.decorators import login_required
from cart.forms import CartAddProductForm
from django.core.paginator import Paginator
from .models import Category, Product, Like, Profile
from .forms import LikeForm, ProfileForm
from . import recommender
from blog.models import Post
from orders.models import Order, OrderItem
from django.views.decorators.http import require_POST
import sys
from django.db.models import Avg, Count


@login_required(login_url="common:login")
def log(request):
    print(request.user.username + " login", file=sys.stdout)
    return redirect("index")


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()

    page = request.GET.get("page", "1")  # 기본 페이지 1, ?page=1
    products = Product.objects.filter(available=True).order_by("-created")

    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)

    paginator = Paginator(products, 15)  # 페이지당 15개
    page_object = paginator.get_page(page)

    return render(
        request,
        "shop/product/list.html",
        {"category": category, "categories": categories, "products": page_object},
    )


def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    like_form = LikeForm()

    recommended_products = recommender.get_recommendations(id, 5)
    # print(recommended_products, file=sys.stdout)
    page = request.GET.get("page", "1")  # 기본 페이지 1, ?page=1

    post_list = Post.objects.filter(product=id).order_by("-created")
    paginator = Paginator(post_list, 5)  # 페이지당 5개
    page_object = paginator.get_page(page)

    if request.user.is_authenticated:
        like_product = Like.objects.filter(
            user=request.user, product=product
        ).values_list("grade")
        if like_product.exists():
            grade = like_product[0][0]
        else:
            grade = 0
    else:
        grade = 0

    all_grade = Like.objects.filter(product=product).aggregate(
        Avg("grade"), Count("grade")
    )
    # print("all_grade: " + str(all_grade), file=sys.stdout)

    # 여기에 계산된 평점을 product.grade에 저장,  product 모델 grade 필드 추가

    return render(
        request,
        "shop/product/detail.html",
        {
            "product": product,
            "grade": grade,
            "all_grade": all_grade,
            "like_form": like_form,
            "post_list": page_object,
            "cart_product_form": cart_product_form,
            "recommended_products": recommended_products,
        },
    )


@login_required()
def profile_create(request):
    if request.method == "POST":
        profile = Profile.objects.filter(user=request.user)
        form = ProfileForm(request.POST)  # 신규 등록시

        for p in profile:  # 기존에 있을 경우 프로필정보 수정
            if p:
                form = ProfileForm(request.POST, instance=p)

        if form.is_valid():
            profile = form.save(commit=False)
            profile.user = request.user
            profile.email = request.user.email
            profile.save()
        return redirect("shop:customer_profile")

    else:
        profile = []
        form = ProfileForm()
        profile = Profile.objects.filter(user=request.user)
        print("profile: " + str(profile), file=sys.stdout)
    return render(
        request, "shop/customer/profile_form.html", {"form": form, "profile": profile}
    )


@login_required()
def profile(request):
    page = request.GET.get("page", "1")  # 기본 페이지 1, ?page=1
    post_list = request.user.author_post.all()
    paginator = Paginator(post_list, 5)  # 페이지당 5개
    page_object = paginator.get_page(page)
    return render(request, "shop/customer/profile.html", {"post_list": page_object})


@login_required()
def ordered_list(request):
    page = request.GET.get("page", "1")  # 기본 페이지 1, ?page=1
    order_list = Order.objects.filter(
        user=request.user.username, paid=True
    ).all()  # 비용 지급한 목록만

    order_items = OrderItem.objects.filter(order__in=order_list)
    # print("order_items: " + str(order_items), file=sys.stdout)

    paginator = Paginator(order_list, 8)  # 페이지당 8개
    page_object = paginator.get_page(page)
    return render(
        request,
        "shop/customer/ordered.html",
        {"order_list": page_object, "order_items": order_items},
    )


# @require_POST
def product_like(request, product_id):
    if request.method == "GET":
        return JsonResponse({"error": "Request isn't POST."}, status=400)

    product = get_object_or_404(Product, id=product_id)

    # print("form.product: " + str( request.POST['product'] ), file=sys.stdout)
    # print("form.user: " + str( request.POST['user'] ), file=sys.stdout)
    print("Ajax form.grade: " + str(request.POST["grade"]), file=sys.stdout)

    # like_product = Like.objects.filter(user=request.user, product=product).values_list('grade')
    # print( like_product[0][0] , file=sys.stdout)

    # AJAX version
    if request.user.is_authenticated:
        like_product = Like.objects.filter(user=request.user, product=product)
    else:
        return JsonResponse({"error": "You aren't authenticated"}, status=400)

    if like_product.exists():
        for like in like_product:
            like.grade = int(request.POST["grade"])
            like.save()
    else:
        Like.objects.create(
            user=request.user, product=product, grade=int(request.POST["grade"])
        )

    all_grade = Like.objects.filter(product=product).aggregate(
        Avg("grade"), Count("grade")
    )
    # print( all_grade , file=sys.stdout)
    # {'grade__avg': 4.0, 'grade__count': 3}

    return JsonResponse(all_grade, status=200)

shop/templates/shop/product/detail.html
{% extends "base.html" %}
{% load static %}
{% load humanize %}
{% load common_filter %}


{% block title %}
  {{ product.name }}
{% endblock %}

{% block content %}
  <div class="container product-detail my-3">
    <img src="{% if product.image %}
        {{ product.image.url }}
      {% else %}
        {% static 'img/no_image.png' %}
      {% endif %}">

    <h1>{{ product.name }}</h1>
    <h2>
      <a href="{{ product.category.get_absolute_url }}">
        {{ product.category }}
      </a>
    </h2>
    <p class="price">{{ product.price|intcomma }}원</p> 

    <form action="{% url 'cart:cart_add' product.id %}" method="post">
      {{ cart_product_form }}
      {% csrf_token %}
      <button type="submit" class="btn btn-primary btn-sm">장바구니추가</button>
    </form> <br/>

    {{ product.contributors }}, {{ product.publisher }}, {{ product.publication_date }}
    <br/><br/>
    {{ product.description|linebreaks }}

 
    {% if request.user.is_authenticated %}

      {{ like_form.media }}
      <form id="like_form">
        {% csrf_token %}
        <input type="hidden" name="user" value="{{ request.user }}">
        <input type="hidden" name="product" value="{{ product.id }}">
        <input type="rating" name="grade" required="" id="id_grade" min="0" max="5" value="{{ grade }}" step="1" style="display:none;">
        <div id="star_id_grade" class="rateit rateit-bg" data-rateit-backingfld="#id_grade"></div> &nbsp;&nbsp;
        <button type="submit" class="btn btn-primary btn-sm mb-2">평점주기</button>
      </form>
    {% endif %}

    <h6>
      <span class="badge badge-warning" id="like_grade">
        {% if all_grade.grade__count > 0 %}
          전체평점: &nbsp;{{ all_grade.grade__avg|floatformat:1 }} 
          ({{ all_grade.grade__count }}명)
        {% endif %}
      </span>
    </h6>

    <br/><hr/>
  </div>


  <div class="d-flex justify-content-center">
    <div class="container">

      {% if recommended_products %}
        <h6>이 상품을 구입하신 분들이 다음 상품도 구입하셨습니다.</h6>

        <div id="main" class="product-list">
            {% for product in recommended_products %}
              <div class="item">
                <a href="{{ product.get_absolute_url }}">
                  <img src="{% if product.image %}
                        {{ product.image.url }}
                    {% else %}
                        {% static 'img/no_image.png' %}
                    {% endif %}"><br/>
                  {{ product.name|truncatechars:30 }}
                </a><br>
                {{ product.price|intcomma }}원
              </div>
            {% endfor %}
        </div>
      {% endif %}

    
    <div class="product_blog">
      <h5>마이리뷰</h5>
    
      <table class="table">
        <tbody>
          {% if post_list %}
            {% for post in post_list %}
              {% if post.status == 'published' %}
                <tr>
                  <td>{{ post_list.paginator.count|sub:post_list.start_index|sub:forloop.counter0|add:1 }}</td>
                  <td>
                    <a href="{% url 'blog:detail' post.id %}">{{ post.title }}</a>
                    {% if post.comment_set.count > 0 %}
                      <span class="text-danger small ml-2">{{ post.comment_set.count }}</span>
                    {% endif %}

                    <div class="post-date text-secondary ml-2">
                      {{ post.author.username }} &nbsp;&nbsp;&nbsp;
                      {{ post.updated| date:'Y.m.d' }}
                    </div>
                  </td>
                </tr>

                <tr>
                  <td>&nbsp</td>
                  <td>{{ post.body|truncatewords:25 }}</td>
                </tr>
              {% endif %}
            {% endfor %}
          {% else %}
            <tr>
              <td colspan="4">본 상품에 대해 등록된 글이 없습니다.</td>
            </tr>
          {% endif %}
        </tbody>
      </table>

      {% include "paginator.html" %}

      <a href="{% url 'blog:post_create' product.id %}" class="btn btn-primary btn-sm">
        글 등록
      </a>
      <br/><br/>
    </div>
  </div>
</div>
{% endblock %}


{% block script %}
<script>
  // On submiting the form, send the POST ajax
  // request to server and after successfull submission display the object.
  $("#like_form").submit(function (e) {
    // preventing from page reload and default actions
    e.preventDefault();

    // serialize the data for sending the form data.
    var serializedData = $(this).serialize();

    $.ajax({               // make POST ajax call
      type: 'POST',
      url: "{% url 'shop:product_like' product.id %}",    
      data: serializedData,

      success: function (response) {
        var grade__avg = JSON.parse(response["grade__avg"]);
        var grade__count = JSON.parse(response["grade__count"]);
        //alert( JSON.parse(response["grade__avg"]) );
        var string_grade = "전체평점: &nbsp;" + grade__avg.toFixed(1) + " (" + grade__count + "명)"

        $("#like_grade").html(string_grade)
      },
      error: function (response) {    // alert the error if any error occured
        alert(response["responseJSON"]["error"]);
      }
    })
  })
</script>
{% endblock %}

shop/templates/shop/product/list.html
{% extends "base.html" %}
{% load static %}
{% load humanize %}


{% block title %}
    {% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}

{% block content %}
    <div class="container my-3">
        <div class="row">
            <div class="col-md-5">
                <select class="form-control category" onchange="if(this.value) location.href=(this.value);">
                    <option value="{% url 'shop:product_list' %}" 
                        {% if not category %}selected{% endif %}>전체</option>

                        {% for c in categories %}
                            <option value="{{ c.get_absolute_url }}" 
                            {% if category.slug == c.slug %}selected{% endif %}>{{ c.name }}</option>
                        {% endfor %}
                </select>
            </div>
            <div class="col-md-7"></div>
        </div>
    </div>


    {% with post_list=products  post=post %}
        <div class="d-flex justify-content-center">
            <div class="container">
                <div id="main" class="product-list">
                    {% for product in products %}
                        <div class="item">
                            <a href="{{ product.get_absolute_url }}">
                            <img src="{% if product.image %}
                                    {{ product.image.url }}
                                {% else %}
                                    {% static 'img/no_image.png' %}
                                {% endif %}">
                            </a> <br/>
                            <a href="{{ product.get_absolute_url }}">{{ product.name|truncatechars:30 }}</a> <br>
                            {{ product.price|intcomma }}원
                        </div>
                    {% endfor %}
                </div>

                {% include "paginator.html" %}
            </div>
        </div>
    {% endwith %}

{% endblock %}