api/urls.py
from rest_framework import routers
from django.urls import path, include
from . import views

app_name = "shop_api"

router = routers.DefaultRouter()

# http://127.0.0.1:8000/api/category/",
# http://127.0.0.1:8000/api/category/1/",

router.register("category", views.CategoryViewSet)
router.register("product", views.ProductViewSet)
router.register("post", views.PostViewSet)
router.register("user", views.UserViewSet)
router.register("order", views.OrderViewSet)


urlpatterns = [
    path("", include(router.urls)),
    path("login/", views.Login.as_view(), name="login"),
    path("signup/", views.Signup.as_view(), name="signup"),
    path(
        "orderitem/<pk>/", views.OrderItemDetailView.as_view(), name="orderitem_detail"
    ),
    path(
        "orderlist/<username>/", views.OrderListDetailView.as_view(), name="order_list"
    ),
    path("iot/", views.iot_esp8266View.as_view()),
    path("getDustData/", views.getDustData.as_view()),
    path("getCoronaData/", views.getCoronaData.as_view()),
    path("getWeatherData/<city>/", views.getWeatherData.as_view()),
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:post_id>/', views.detail, name='detail'),
    path('create/<int:product_id>', views.post_create, name='post_create'),
    path('modify/<int:post_id>/', views.post_modify, name='post_modify'),
    path('delete/<int:post_id>/', views.post_delete, name='post_delete'),

    path('vote/<int:post_id>', views.post_vote, name='post_vote'),

    path('<int:post_id>/comment/create/', views.comment_create, name='comment_create'),
    path('comment/modify/<int:comment_id>/', views.comment_modify, name='comment_modify'),
    path('comment/delete/<int:comment_id>/', views.comment_delete, name='comment_delete'),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from shop.models import Product
from django.utils import timezone


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', '비공개'), ('published', '공개'),
    )
    title = models.CharField(max_length=250)
    body = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_post')

    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    #publish = models.DateTimeField(default=timezone.now)       #admin, for date_hierarchy 
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='published')

    voter = models.ManyToManyField(User, related_name='voter_post')
    #post.voter.all() = <QuerySet [<User: admin>, <User: ojonghwa>]>  
    #post.author.voter_post.all() = [<QuerySet [<Post: 공부해 봅시다.>, <Post: 도킨스가 칭찬할 만하다>,
    #request.user.voter_post.all()  #조회
    
    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return self.title


class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    class Meta:
        ordering = ('created',)
        

blog/forms.py
from django import forms
from blog.models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'body', 'product', 'status']
        widgets = {
            'title' : forms.TextInput(attrs={'class':'form-control'}), 
            #'author': forms.Select(attrs={'class':'form-control'}), 
            'body'  : forms.Textarea(attrs={'class':'form-control', 'rows':'10'}), 
            'product': forms.Select(attrs={'class':'form-control'}),
            'status': forms.Select(attrs={'class':'form-control'}),
        }
        labels = {
            'title' : '제목', 
            'body'  : '내용', 
            'product': '제품',
            'status': '공개 여부',
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        labels = {
            'content': '댓글내용',
        }

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.utils import timezone
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .models import Post, Comment
from .forms import PostForm, CommentForm
from django.db.models import Q, Count
from django.http import JsonResponse
from django.views.decorators.http import require_POST
from shop.models import Product
import sys


def index(request):
    page = request.GET.get('page','1')      # 기본 페이지 1, ?page=1
    kw = request.GET.get('kw', '')          # 검색어
    so = request.GET.get('so', 'recent')    # 정렬기준
    #print('kw=' + kw, file=sys.stdout)

    if so == 'recommend':       # 정렬
        post_list = Post.objects.annotate(num_voter=Count('voter')).order_by('-num_voter', '-created')
    else:       # recent
        post_list = Post.objects.order_by('-created')

    if kw:      # 검색
        post_list = post_list.filter(
            Q(title__icontains=kw) |        # 제목검색
            Q(body__icontains=kw)  |        # 내용검색
            Q(author__username__icontains=kw)     # 작성자검색
        ).distinct()

    paginator = Paginator(post_list, 7)     # 페이지당 7개 표시 
    page_object = paginator.get_page(page)

    products = Product.objects.order_by('name')
    if kw:      # 검색
        products = products.filter(
            Q(name__icontains=kw) |         # 제목검색
            Q(description__icontains=kw)    # 내용검색
        ).distinct()
    else:
        products = None

    return render(request, 'blog/post_list.html', 
        { 'post_list': page_object, 'page': page, 'kw': kw, 'so': so, 'products': products })



def detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    return render(request, 'blog/post_detail.html', { 'post': post, 'product': post.product })



@login_required(login_url='common:login')
def post_create(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user      # post 작성자 id 추가 
            post.save()
            return redirect('blog:index')
    else:
        form = PostForm()
    return render(request, 'blog/post_form.html', {'form':form, 'product':product })



@login_required(login_url='common:login')
def post_modify(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    product = get_object_or_404(Product, id=post.product.id)
    #print(post, file=sys.stdout)

    if request.user != post.author:
        messages.error(request, '수정권한이 없습니다.')
        return redirect('blog:detail', post_id=post.id)

    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.updated = timezone.now()       # 수정일시
            post.save()
            return redirect('blog:detail', post_id=post.id)
    else:
        form = PostForm(instance=post)

    return render(request, 'blog/post_form.html', {'form': form, 'product':product })



@login_required(login_url='common:login')
def post_delete(request, post_id):
    post = get_object_or_404(Post, id=post_id)

    if request.user != post.author:
        messages.error(request, '삭제권한이 없습니다')
        return redirect('blog:detail', post_id=post.id)

    post.delete()
    return redirect('blog:index')



@login_required()
@require_POST
def post_vote(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    action = request.POST.get('action')

    if request.is_ajax:
        print("Ajax action: " + action, file=sys.stdout)

    if post and action:
        try:
            if action == 'vote':
                post.voter.add(request.user)        # 추천
                #request.user.voter_post.add(post)  # 위와 동일함
            else:
                post.voter.remove(request.user)     # 추천 취소
                #request.user.voter_post.remove(post)
            return JsonResponse({'status':'ok'})
        except:
            pass
    return JsonResponse({'status':'error'})



@login_required(login_url='common:login')
def comment_create(request, post_id):
    post = get_object_or_404(Post, pk=post_id)

    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.post = post
            comment.save()
            return redirect('{}#comment_{}'.format(
                resolve_url('blog:detail', post_id=comment.post.id), comment.id))   # 스크롤 처리 앵커
    else:
        form = CommentForm()
    return render(request, 'blog/comment_form.html', {'form': form})



@login_required(login_url='common:login')
def comment_modify(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '댓글 수정권한이 없습니다')
        return redirect('blog:detail', post_id=comment.post.id)

    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.updated = timezone.now()
            comment.save()
            return redirect('{}#comment_{}'.format(
                resolve_url('blog:detail', post_id=comment.post.id), comment.id))
    else:
        form = CommentForm(instance=comment)
    return render(request, 'blog/comment_form.html', {'form': form})



@login_required(login_url='common:login')
def comment_delete(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '댓글 삭제권한이 없습니다')
        return redirect('blog:detail', post_id=comment.post_id)
    else:
        comment.delete()
    return redirect('blog:detail', post_id=comment.post_id)

blog/templates/blog/comment_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container my-3">
    <h5 class="border-bottom pb-2">댓글 등록하기</h5>
    <form method="post" class="post-form my-3">
        {% csrf_token %}
        
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="content">댓글내용</label>
            <textarea class="form-control" name="content" id="content" 
                rows="3">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary btn-sm">저장하기</button>
    </form>
</div>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="container my-3">
    <h5 class="border-bottom py-2">{{ post.title }}</h5>

    <div class="card my-3">
        <div class="card-body product-detail">
            <div class="card-text">
                <a href="{{ product.get_absolute_url }}" class="badge badge-primary p-2">
                    책: {{ product.name }}
                </a><br/><br/>
                {{ post.body }}
            </div>

            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2 text-left">
                    <div class="mb-2">{{ post.author.username }}</div>
                    <div>{{ post.updated| date:'Y.m.d H:i' }}</div>
                </div>
            </div>

            <div class="d-flex justify-content-start">
                {% if request.user == post.author %}
                    <h6 class="like">
                        <a href="{% url 'blog:post_modify' post.id  %}"
                            class="btn btn-sm btn-outline-secondary">수정</a>&nbsp;
                        <a href="{% url 'blog:post_delete' post.id  %}"
                            class="btn btn-sm btn-outline-secondary">삭제</a>&nbsp;&nbsp;
                        
                        <a href="#" class="badge badge-secondary p-2">
                            <span class="total_count">{{ post.voter.count }}</span>
                            &nbsp; 추천</a>
                    </h6>
                {% else %}

                    {% if request.user in post.voter.all %}
                        <h6 class="cancel">
                            <a href="#" data-id="{{ post.id }}" data-action="cancel" 
                                class="like badge badge-primary p-2">
                                <span class="total_count">{{ post.voter.count }}</span>&nbsp; 추천
                            </a>
                        </h6>
                    {% else %}
                        <h6 class="vote">
                            <a href="#" data-id="{{ post.id }}" data-action="vote" 
                                class="like badge badge-secondary p-2">
                                <span class="total_count">{{ post.voter.count }}</span>&nbsp; 추천
                            </a>
                        </h6>
                    {% endif %}

                {% endif %}
            </div>
        </div>


        <!-- 댓글 Start -->
        <div>
            <a href="{% url 'blog:comment_create' post.id  %}"
               class="small px-4"><medium>댓글 추가 ..</medium></a>
        </div>

        {% if post.comment_set.count > 0 %}
            <div class="mt-1">
                {% for comment in post.comment_set.all %}
                    <a name="comment_{{ comment.id }}"></a>     <!-- 댓글 앵커 엘리먼트 추가 -->
                    <div class="comment py-1 text-muted">
                        <span style="white-space: pre-line;">{{ comment.content }}</span>
                        <span class="badge badge-light p-2">- {{ comment.author }}, {{ comment.updated| date:'Y.m.d H:i' }}
                        </span>
                        {% if request.user == comment.author %}
                            <a href="{% url 'blog:comment_modify' comment.id  %}" class="small">수정</a>,
                            <a href="{% url 'blog:comment_delete' comment.id  %}" class="small delete">삭제</a>
                        {% endif %}
                    </div>
                {% endfor %}
            </div>
        {% endif %}
        <!-- 댓글 End -->

    </div>
</div>
{% endblock %}


{% block domready %}
    $('a.like').click(function(e) {     // AJAX
        e.preventDefault();
        $.post('{% url "blog:post_vote" post.id %}', 
            { id: $(this).data('id'), action: $(this).data('action') },

            function(data) {
                if (data['status'] == 'ok') {
                    var previous_action = $('a.like').data('action');

                    // toggle data-action
                    $('a.like').data('action', previous_action == 'vote' ? 'cancel' : 'vote');

                    // update total likes
                    var previous_likes = parseInt($('span.total_count').text());
                    $('span.total_count').text(previous_action == 'vote' ? previous_likes + 1 : previous_likes - 1);

                    if( $('a.like').hasClass('badge-secondary') ) {
                        $('a.like').removeClass('badge-secondary');
                        $('a.like').addClass('badge-primary');
                    } else {
                        $('a.like').removeClass('badge-primary');
                        $('a.like').addClass('badge-secondary');
                    }
                }
            }
        );
    });
{% endblock %}

blog/templates/blog/post_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container my-3">
    <h4 class="border-bottom py-2">글 등록</h4>

    <form method="post" class="my-3">
        {% csrf_token %}

        {% include "form_errors.html" %}

        <div class="form-group">
            <label for="title">제목</label>
            <input type="text" name="title" id="title" class="form-control" 
                value="{{ form.title.value|default_if_none:'' }}">
            
            <label for="body" class="my-3">내용</label>
            <textarea name="body" id="body" {% if not user.is_authenticated %}disabled{% endif %}
                rows="7" class="form-control">{{ form.body.value|default_if_none:'' }}</textarea>
            
            <label for="product" class="my-3">제품:</label>
            <select class="form-control" name="product" id="product"> 
                <option class="form-control" value="{{ product.id }}" selected>
                {{ product.name }}</option>
            </select>
     
            <label for="status" class="my-3">공개 여부:</label>
            <select name="status" class="form-control" id="status">
                <option value="draft">비공개</option>
                <option value="published" selected>공개</option>
            </select>
         
        </div>
        <input type="submit" value="저장" class="btn btn-primary btn-sm">
    </form>

</div>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'base.html' %}
{% load static %}
{% load common_filter %}
{% load humanize %}


{% block content %}

<div class="container my-3">
    <h5 class="border-bottom py-3">{% if kw %}'{{ kw }}' 검색결과{% endif %}</h5>

    <div class="product-list">
        {% for product in products %}
          <div class="item">
            <a href="{{ product.get_absolute_url }}">
              <img src="{% if product.image %}
                  {{ product.image.url }}
                {% else %}
                  {% static 'img/no_image.png' %}
                {% endif %}">
            </a><br/>

            <a href="{{ product.get_absolute_url }}">{{ product.name|truncatechars:30 }}</a><br>
            {{ product.price|intcomma }}원
          </div>
        {% endfor %}
    </div>


    <div >
        <select class="form-control so">
            <option value="recent" {% if so == 'recent' %}selected{% endif %}>최신순</option>
            <option value="recommend" {% if so == 'recommend' %}selected{% endif %}>추천순</option>
        </select>
    </div>

    
    <table class="table my-3">
        <tbody>
            {% if post_list %}
                {% for post in post_list %}
                    {% if post.status == 'published' %}
                    <tr class="text-center">
                        <td>{{ post_list.paginator.count|sub:post_list.start_index|sub:forloop.counter0|add:1 }}</td>

                        <td class="text-left">
                            <a href="{% url 'blog:detail' post.id %}">{{ post.title|truncatechars:35 }}</a>
                            {% if post.comment_set.count > 0 %}
                                <span class="text-danger small ml-2">{{ post.comment_set.count }}</span>
                            {% endif %}
                        </td>

                        <td>{{ post.author.username }}</td>
                        <td>{{ post.updated| date:'Y-m-d H:i' }}</td>
                    </tr>
                    {% endif %}
                {%  endfor %}
            {% else %}
                <tr>
                    <td colspan="4">등록된 글이 없습니다.</td>
                </tr>
            {% endif %}
        </tbody>
    </table>

    {% include "paginator2.html" %}
   
</div>
{% endblock %}