api/urls.py
from rest_framework import routers
from django.urls import path, include
from . import views

app_name = "shop_api"

router = routers.DefaultRouter()

# http://127.0.0.1:8000/api/category/",
# http://127.0.0.1:8000/api/category/1/",

router.register("category", views.CategoryViewSet)
router.register("product", views.ProductViewSet)
router.register("post", views.PostViewSet)
router.register("user", views.UserViewSet)
router.register("order", views.OrderViewSet)


urlpatterns = [
    path("", include(router.urls)),
    path("login/", views.Login.as_view(), name="login"),
    path("signup/", views.Signup.as_view(), name="signup"),
    path(
        "orderitem/<pk>/", views.OrderItemDetailView.as_view(), name="orderitem_detail"
    ),
    path(
        "orderlist/<username>/", views.OrderListDetailView.as_view(), name="order_list"
    ),
    path("iot/", views.iot_esp8266View.as_view()),
    path("getDustData/", views.getDustData.as_view()),
    path("getCoronaData/", views.getCoronaData.as_view()),
    path("getWeatherData/<city>/", views.getWeatherData.as_view()),
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:post_id>/', views.detail, name='detail'),
    path('create/<int:product_id>', views.post_create, name='post_create'),
    path('modify/<int:post_id>/', views.post_modify, name='post_modify'),
    path('delete/<int:post_id>/', views.post_delete, name='post_delete'),

    path('vote/<int:post_id>', views.post_vote, name='post_vote'),

    path('<int:post_id>/comment/create/', views.comment_create, name='comment_create'),
    path('comment/modify/<int:comment_id>/', views.comment_modify, name='comment_modify'),
    path('comment/delete/<int:comment_id>/', views.comment_delete, name='comment_delete'),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change_form.html', success_url='done'), 
        name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), 
        name='password_change_done'),

    path('password_reset/', auth_views.PasswordResetView.as_view(success_url='done'), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(success_url=reverse_lazy('common:login')), name='password_reset_confirm'),
    #path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),
]

shop/urls.py
from django.urls import path
from . import views

app_name = "shop"

urlpatterns = [
    path("", views.product_list, name="product_list"),
    path("<slug:category_slug>/", views.product_list, name="product_list_by_category"),
    path("<int:id>/<slug:slug>/", views.product_detail, name="product_detail"),
    path("customer/profile/", views.profile, name="customer_profile"),
    path(
        "customer/profile/create/", views.profile_create, name="customer_profile_create"
    ),
    path("customer/ordered_list/", views.ordered_list, name="customer_ordered_list"),
    path("product/like/<int:product_id>", views.product_like, name="product_like"),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}?v4">

    <link rel="shortcut icon" type="image/x-icon" href="{% static 'favicon.ico' %}">
    <title>{% block title %}My shop{% endblock %}</title>
</head>

<body>
    <!-- 네비게이션바 -->
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{% url 'index' %}"><B>Book Cafe24</B></a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
                <span class="navbar-toggler-icon"></span>
            </button>
        
            <div class="collapse navbar-collapse" id="navbarSupportedContent">

                <!-- 추후 메뉴 추가 
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link navi-menu" href="#">메뉴1</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle navi-menu" href="#" data-toggle="dropdown">메뉴2</a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item navi-menu" href="#">아이템1</a>
                            <a class="dropdown-item navi-menu" href="#">아이템2</a>
                            <a class="dropdown-item navi-menu" href="#">아이템3</a>
                        </div>
                    </li>
                </ul>
                -->

                <ul class="navbar-nav ml-auto ">

                    {% with total_items=cart|length %}
                        <li class="nav-item">
                            <a class="nav-link navi-menu" href="{% url 'cart:cart_detail' %}">장바구니[{{ total_items }}]</a>
                        </li>
                    {% endwith %}

                    {% if user.is_authenticated %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle navi-menu" href="#" data-toggle="dropdown">{{ user.username }}</a>

                            <div class="dropdown-menu">
                                <a class="dropdown-item navi-menu" href="{% url 'shop:customer_profile' %}">프로필</a>    
                                <a class="dropdown-item navi-menu" href="{% url 'common:password_change' %}">비밀번호 변경</a>
                                <!-- <div class="dropdown-divider"></div> -->
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link navi-menu" href="{% url 'common:logout' %}">로그아웃</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link navi-menu" href="{% url 'common:signup' %}">회원가입</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link navi-menu" href="{% url 'common:login' %}">로그인</a>
                        </li>
                    {% endif %}
                </ul>

                <div class="form-inline">
                    <input class="kw form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search" value="">
                    <button class="btn btn-outline-success my-2" type="submit" id="btn_search">검색</button>
                </div>
            </div>
        </nav>

        {% if messages %}
            {% for message in messages %}
                <div class="row" style="margin:20px auto;">
                    <div class="col-sm-12">
                        <div class="alert alert-danger">
                            <strong>{{ message.tags }}!</strong> {{ message.message }}
                        </div>
                    </div>
                </div>
            {% endfor %}
        {% endif %}
    </div>
    

    {% block content %}
    {% endblock %}

    <form id="searchForm" method="get" action="{% url 'blog:index' %}">
        <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
        <input type="hidden" id="page" name="page" value="{{ page }}">
        <input type="hidden" id="so" name="so" value="{{ so }}">
    </form>

    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/js-cookie@2.2.1/src/js.cookie.min.js"></script>
    <script>
        var csrftoken = Cookies.get('csrftoken');
        function csrfSafeMethod(method) {
            // these HTTP methods do not require CSRF protection
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }
        $.ajaxSetup({
            beforeSend: function(xhr, settings) {
                if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", csrftoken);
                }
            }
        });

        $(document).ready(function() {
            {% block domready %}

            {% endblock %}
        });
    </script>

    <script type='text/javascript'>
        $(document).ready(function() {
            $(".page-link").on('click', function() {
                $("#page").val($(this).data("page"));
                $("#searchForm").submit();
            });

            $("#btn_search").on('click', function() {
                $("#kw").val($(".kw").val());
                $("#page").val(1);      // 검색버튼을 클릭할 경우 1페이지부터 조회
                $("#searchForm").submit();
            });

            $(".so").on('change', function() {  // 정렬기준
                $("#so").val($(this).val());
                $("#page").val(1);
                $("#searchForm").submit();
            });
        });
    </script>


    {% block script %}
    {% endblock %}

</body>
</html>

templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}     <!-- 필드 오류를 출력한다. -->
            <div class="alert alert-danger">
                <button type="button" class="close" data-dismiss="alert">&times</button>
                <strong>{{ field.label }} </strong>- {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    
    {% for error in form.non_field_errors %}   <!-- 넌필드 오류를 출력한다. -->
        <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert">&times</button>
            {{ error }}
        </div>
    {% endfor %}
{% endif %}

templates/paginator.html
{% if post_list %}
    <!-- 페이징처리 시작 -->
    <ul class="pagination pagination-sm">

        <!-- 이전페이지 -->
        {% if post_list.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{post_list.previous_page_number}}">&laquo;</a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <a class="page-link" tabindex="-1" href="#">&laquo;</a>
            </li>
        {% endif %}

        <!-- 페이지리스트 -->
        {% for page_number in post_list.paginator.page_range %}
            {% if page_number >= post_list.number|add:-3 and page_number <= post_list.number|add:3 %}
                {% if page_number == post_list.number %}
                    <li class="page-item active" aria-current="page">
                        <a class="page-link" href="?page={{page_number}}">{{ page_number }}</a>
                    </li>
                {% else %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{page_number}}">{{ page_number }}</a>
                    </li>
                {% endif %}
            {% endif %}
        {% endfor %}

        <!-- 다음페이지 -->
        {% if post_list.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{post_list.next_page_number}}">&raquo;</a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <a class="page-link" tabindex="-1" href="#">&raquo;</a>
            </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->
{% endif %}

templates/paginator2.html
{% if post_list %}
<!-- 페이징처리 시작 -->
<ul class="pagination pagination-sm justify-content-center">

    <!-- 이전페이지 -->
    {% if post_list.has_previous %}
        <li class="page-item">
            <a class="page-link" data-page="{{ post_list.previous_page_number }}" href="#">&laquo;</a>
        </li>
    {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">&laquo;</a>
        </li>
    {% endif %}

    <!-- 페이지리스트 -->
    {% for page_number in post_list.paginator.page_range %}
        {% if page_number >= post_list.number|add:-3 and page_number <= post_list.number|add:3 %}
            {% if page_number == post_list.number %}
                <li class="page-item active" aria-current="page">
                    <a class="page-link" data-page="{{ page_number }}" href="#">{{ page_number }}</a>
                </li>
            {% else %}
                <li class="page-item">
                    <a class="page-link" data-page="{{ page_number }}" href="#">{{ page_number }}</a>
                </li>
            {% endif %}
        {% endif %}
    {% endfor %}

    <!-- 다음페이지 -->
    {% if post_list.has_next %}
        <li class="page-item">
            <a class="page-link" data-page="{{ post_list.next_page_number }}" href="#">&raquo;</a>
        </li>
    {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">&raquo;</a>
        </li>
    {% endif %}
</ul>
<!-- 페이징처리 끝 -->
{% endif %}